// 🕷️ FRASES DE SPIDER-HÉROES MULTIVERSO
const frasesSpiderHeroes = {
  scarletSpider: [
    "Soy Ben Reilly... el clon con corazón.",
    "No soy Peter... pero soy Spider-Man.",
    "No corro de mi pasado, lo enfrento.",
    "Los errores no me definen. Mis actos, sí.",
    "Soy la cicatriz viviente del legado de Parker.",
    "Clonado, confundido... pero nunca rendido.",
    "Cada telaraña que lanzo busca redención.",
    "No pedí esta vida, pero la vivo con honor.",
    "Soy el otro... pero también soy héroe.",
    "Clon o no, la ciudad me necesita."
  ],
  superiorSpider: [
    "Otto Octavius... el Spider-Man superior.",
    "Ahora el intelecto lidera al héroe.",
    "El crimen será erradicado. Lógica pura.",
    "Sentimientos fuera. Solo eficiencia.",
    "No soy amable, soy necesario.",
    "El viejo Parker era débil. Yo no lo soy.",
    "Redefinir al héroe, redefinir el poder.",
    "No más culpa. Solo resultados.",
    "¿Moralidad? Prefiero resultados cuantificables.",
    "Mis Spider-Bots vigilan cada rincón de la ciudad."
  ],
  spiderHam: [
    "¿A quién llamás puerco?",
    "Peter Porker, ¡el cerdo arácnido!",
    "Salvando al mundo... con humor y jamón.",
    "¿Multiverso? ¡Yo nací en la locura!",
    "Soy más que una broma, soy un héroe.",
    "¡Jamás subestimes a un Spider-Ham!",
    "¿Arañas? ¿Cerdos? ¡Sí!",
    "Spider-Sense... con aroma a tocino.",
    "¡Mi poder viene con mucha grasa!",
    "Cuando el deber llama, oink."
  ],
  killerSpider: [
    "Yo hice lo que los otros no se atreven.",
    "¿Líneas que no se cruzan? Ya las crucé.",
    "La justicia tiene un nuevo precio.",
    "No soy cruel, soy necesario.",
    "El fin justifica las telarañas.",
    "Un poder oscuro... pero útil.",
    "El multiverso no necesita héroes. Necesita decisiones.",
    "Spider-Man... sin frenos morales.",
    "Fui un héroe. Ahora soy una advertencia.",
    "Ya no soy el chico bueno de siempre."
  ],
  spiderNoir: [
    "Trabajo solo... y en sombras.",
    "La ciudad tiene secretos. Yo los descubro.",
    "No necesito colores brillantes para ser Spider-Man.",
    "Nací en una época oscura. Me adapté.",
    "Donde otros ven telarañas, yo veo pistas.",
    "Cada crimen deja un hilo. Yo lo sigo.",
    "El dolor no me detiene. Me guía.",
    "Spider-Man, versión tinta y plomo.",
    "Un héroe de sombrero... y justicia.",
    "Mi voz es grave. Mi misión, más aún."
  ],
  spiderPunk: [
    "¡Contra el sistema, con estilo!",
    "Spider-Punk no se somete.",
    "Telarañas y guitarras, mi revolución.",
    "El poder es del pueblo. Y mío también.",
    "Rompo las reglas. Armo nuevas.",
    "El multiverso necesita ruido.",
    "Las telarañas se combinan con riffs.",
    "¿Autoridad? ¡Ja, buena suerte!",
    "Mi traje grita rebeldía.",
    "Cada salto es un grito punk."
  ],
  spiderGwen: [
    "Desde mi universo, lucho con ritmo.",
    "No soy un reflejo. Soy única.",
    "Perdí mucho. Ahora lucho por todos.",
    "Spider-Gwen. O Ghost-Spider. Elegí uno.",
    "La música me da fuerza. La justicia, propósito.",
    "Peter me inspiró. Yo elijo proteger.",
    "No estoy sola, tengo mi sonido.",
    "Telarañas con eco. Golpes con ritmo.",
    "Cada salto es una nota rebelde.",
    "La culpa no me detiene. Me impulsa."
  ],
  peniParker: [
    "SP//dr listo para patrullar.",
    "Mi padre me dejó este legado.",
    "No soy solo una niña. Soy piloto.",
    "La sinergia entre mente y máquina.",
    "SP//dr y yo somos uno.",
    "Mi coraje es programado con humanidad.",
    "Multiverso, prepárate para la ciencia anime.",
    "En mi mundo, ser Spider no es biológico.",
    "El futuro es ahora, y yo estoy pilotando.",
    "¿Arácnidos? Yo tengo mechas."
  ],
  spider2099: [
    "Miguel O'Hara. Spider-Man del mañana.",
    "La genética también puede ser heroica.",
    "Nueva York 2099 necesita justicia.",
    "No soy Parker, pero sigo sus pasos.",
    "Tecnología avanzada. Honor intacto.",
    "Cada salto lleva análisis cuántico.",
    "Spider-Man 2099: precisión absoluta.",
    "Los errores del pasado no se repiten.",
    "El futuro tiene telarañas también.",
    "Mi traje es ciencia. Mi misión, eterna."
  ],
  ps4Peter: [
    "Tu amigable vecino... de otra consola.",
    "Los quick-time events no me detienen.",
    "Balancearse nunca se sintió tan fluido.",
    "Me enfrenté a todos. Y aún sonrío.",
    "Trabajo, amor, villanos... soy multitarea.",
    "Esta ciudad me entrenó... con trofeos.",
    "Peter Parker, versión gamer.",
    "MJ, Miles... siempre a mi lado.",
    "Octavius fue mi peor error... y mi mayor lección.",
    "Spider-Man, con mejoras desbloqueadas."
  ],
  andrewPeter: [
    "Soy el Spider-Man raro. Pero sigo luchando.",
    "Gwen me enseñó el valor de seguir.",
    "No soy perfecto. Pero doy todo.",
    "Mi telaraña viene con trauma incluido.",
    "La red no siempre atrapa... pero yo sigo tirando.",
    "Quise ser mejor. Todavía lo intento.",
    "Lucho por los que no pueden.",
    "Soy Peter. Caído, pero en pie.",
    "A veces río... para no llorar.",
    "Redención es mi motor."
  ],
  tobeyPeter: [
    "¡Mi espalda! ...pero sigo.",
    "Soy el primer Spider del multiverso cinematográfico.",
    "El vecino original ha vuelto.",
    "Los dedos aún lanzan telarañas... naturales.",
    "Mary Jane, Harry... siempre en mi corazón.",
    "El dolor forma parte del deber.",
    "Un gran poder... ya sabés cómo sigue.",
    "Peter Parker. El OG.",
    "Luché contra el Duende, Otto... y la renta.",
    "Sigo siendo tu Spider-Man de siempre."
  ],
  tomPeter: [
    "¿Hola? ¿Alguien más tiene telarañas aquí?",
    "Tony Stark creyó en mí.",
    "No soy Iron Man. Soy Spider-Man.",
    "Solo quería ser el héroe de mi barrio.",
    "Mi traje habla. Literal.",
    "Perdí mucho... pero sigo en pie.",
    "¿Viajes espaciales? Checklist hecho.",
    "No soy un Vengador... soy Peter.",
    "MJ, Ned... son mi familia.",
    "La responsabilidad me sigue... y la acepto."
  ],
  spider2211: [
    "Tiempo, espacio... lo controlo todo.",
    "Spider-Man 2211: conectado a todo.",
    "Tecnodrones listos para vigilancia.",
    "Mi telaraña es cuántica.",
    "Multiverso asegurado por protocolos.",
    "Soy futuro, soy vigilancia.",
    "La red... ahora es interdimensional.",
    "Peter Parker... versión tiempo total.",
    "Spider-Man con núcleo temporal.",
    "Vine desde el futuro... para salvar el presente."
  ],
  captainUniverse: [
    "El Enigma Force fluye a través de mí.",
    "Poder absoluto. Voluntad inquebrantable.",
    "Soy el cosmos en forma de héroe.",
    "Las estrellas me obedecen.",
    "Spider-Man... versión universal.",
    "El multiverso se inclina ante este poder.",
    "No soy un dios... pero lo parezco.",
    "Peter Parker... canal del infinito.",
    "El equilibrio cósmico está en mis manos.",
    "Capitán Universo. Guardián del todo."
  ]
};
